{{- if .Values.daemon.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bd-daemon.fullname" . }}
  labels:
    {{- include "bd-daemon.labels" . | nindent 4 }}
type: Opaque
data:
  daemon-token: {{ .Values.daemon.token | b64enc | quote }}
{{- end }}
