{{- if .Values.dolt.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bd-daemon.dolt.serviceAccountName" . }}
  labels:
    {{- include "bd-daemon.dolt.labels" . | nindent 4 }}
  {{- with .Values.dolt.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.daemon.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bd-daemon.daemon.serviceAccountName" . }}
  labels:
    {{- include "bd-daemon.daemon.labels" . | nindent 4 }}
  {{- with .Values.daemon.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
