apiVersion: v1
kind: Service
metadata:
  name: {{ include "bd-daemon.daemon.fullname" . }}
  labels:
    {{- include "bd-daemon.daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.daemon.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.daemon.service.port | default 9876 }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    {{- if .Values.daemon.http.enabled }}
    - port: {{ .Values.daemon.service.httpPort | default 9080 }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "bd-daemon.daemon.selectorLabels" . | nindent 4 }}
